import { parseSlackInputResponse } from "@chat-adapter/slack/blocks";
import {
  readSlackWebhook,
  SlackWebhookParseError,
  SlackWebhookVerificationError,
} from "@chat-adapter/slack/webhook";
import type {
  DeliveryRetry,
  InteractionSurfaceEvent,
  SurfaceEvent,
  SurfaceIngressDriver,
  SurfaceRef,
} from "#chat/contracts.js";
import { SurfaceDriverError } from "#chat/errors.js";
import type { SlackDriverOptions } from "#chat/slack/contracts.js";

/** Stable action id for a stop button whose value is the targeted run id. */
export const SLACK_STOP_ACTION_ID = "trema:stop";

export class SlackIngressDriver implements SurfaceIngressDriver {
  readonly #options: { now?: SlackDriverOptions["now"]; signingSecret: string };

  constructor(options: { now?: SlackDriverOptions["now"]; signingSecret: string }) {
    this.#options = options;
  }

  async read(request: Request): Promise<SurfaceEvent> {
    try {
      const payload = await readSlackWebhook(request, {
        signingSecret: this.#options.signingSecret,
        ...(this.#options.now === undefined ? {} : { now: this.#options.now }),
      });
      const retry = toRetry(payload.retry);

      if (payload.kind === "url_verification") {
        return { type: "challenge", surface: "slack", challenge: payload.challenge, ...retry };
      }
      if (payload.kind === "app_mention" || payload.kind === "direct_message") {
        const authorRef = payload.userId;
        if (authorRef === undefined || authorRef.length === 0) {
          return unsupported("message-without-author", payload.raw, retry);
        }
        return {
          type: "message",
          surface: "slack",
          intentId: `slack:event:${payload.eventId ?? `${payload.channelId}:${payload.ts}`}`,
          surfaceRef: toSurfaceRef(payload.continuation, authorRef),
          authorRef,
          text: payload.text,
          at: slackTimestamp(payload.eventTime, payload.ts),
          nativeMessageRef: payload.ts,
          nativeKind: payload.kind === "app_mention" ? "app-mention" : "direct-message",
          ...retry,
        };
      }
      if (payload.kind === "block_actions") {
        const action = payload.actions[0];
        if (action === undefined) return unsupported("block_actions:empty", payload.raw, retry);
        const resolution = parseSlackInputResponse(action);
        const stop = parseStopAction(action.actionId, action.value);
        const event: InteractionSurfaceEvent = {
          type: "interaction",
          surface: "slack",
          intentId: `slack:interaction:${payload.triggerId ?? `${payload.userId}:${payload.messageTs ?? "unknown"}:${action.actionId}`}`,
          authorRef: payload.userId,
          action:
            resolution?.optionId === undefined
              ? (stop ?? {
                  type: "native",
                  actionId: action.actionId,
                  ...(action.value === undefined ? {} : { value: action.value }),
                })
              : {
                  type: "resolve",
                  elicitationId: resolution.requestId,
                  optionId: resolution.optionId,
                },
          ...(payload.continuation === undefined
            ? {}
            : { surfaceRef: toSurfaceRef(payload.continuation, payload.userId) }),
          ...retry,
        };
        return event;
      }
      if (payload.kind === "unsupported") {
        const reply = threadedReply(payload.raw, retry);
        if (reply !== undefined) return reply;
      }
      return unsupported(
        payload.kind === "unsupported" ? payload.type : payload.kind,
        payload.raw,
        retry,
      );
    } catch (error) {
      if (error instanceof SlackWebhookVerificationError) {
        throw new SurfaceDriverError("Slack webhook verification failed", {
          category: "invalid-request",
          cause: error,
          method: "webhook.verify",
          retryable: false,
        });
      }
      if (error instanceof SlackWebhookParseError) {
        throw new SurfaceDriverError("Slack webhook parsing failed", {
          category: "invalid-request",
          cause: error,
          method: "webhook.parse",
          retryable: false,
        });
      }
      throw error;
    }
  }
}

/**
 * Stop controls are Trema-owned, unlike elicitation controls generated by
 * Chat SDK. The run id lives in both fields so a renderer can use a stable
 * action id while Slack preserves the target in the button value.
 */
function parseStopAction(
  actionId: string,
  value: string | undefined,
): InteractionSurfaceEvent["action"] | undefined {
  if (actionId === SLACK_STOP_ACTION_ID && value) return { type: "stop", runId: value };
  const prefix = `${SLACK_STOP_ACTION_ID}:`;
  if (actionId.startsWith(prefix) && actionId.length > prefix.length) {
    return { type: "stop", runId: actionId.slice(prefix.length) };
  }
  return undefined;
}

/**
 * Chat SDK deliberately returns unknown Events API shapes as unsupported.
 * A plain human reply in a channel thread is one of those shapes, so validate
 * that narrow payload here and keep every Slack-native field at the boundary.
 */
function threadedReply(raw: unknown, retry: { retry?: DeliveryRetry }): SurfaceEvent | undefined {
  const envelope = asRecord(raw);
  const native = asRecord(envelope.event);
  if (
    native.type !== "message" ||
    typeof native.thread_ts !== "string" ||
    typeof native.ts !== "string" ||
    typeof native.channel !== "string" ||
    typeof native.user !== "string" ||
    typeof native.text !== "string" ||
    native.bot_id !== undefined ||
    native.subtype !== undefined
  ) {
    return undefined;
  }
  const workspaceId = stringValue(envelope.team_id);
  const enterpriseId = stringValue(envelope.enterprise_id);
  const continuation = {
    channelId: native.channel,
    threadTs: native.thread_ts,
    ...(workspaceId === undefined ? {} : { teamId: workspaceId }),
    ...(enterpriseId === undefined ? {} : { enterpriseId }),
  };
  return {
    type: "message",
    surface: "slack",
    intentId: `slack:event:${stringValue(envelope.event_id) ?? `${native.channel}:${native.ts}`}`,
    surfaceRef: toSurfaceRef(continuation, native.user),
    authorRef: native.user,
    text: native.text,
    at: slackTimestamp(
      typeof envelope.event_time === "number" ? envelope.event_time : undefined,
      native.ts,
    ),
    nativeMessageRef: native.ts,
    nativeKind: "thread-reply",
    ...retry,
  };
}

function asRecord(value: unknown): Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : {};
}

function stringValue(value: unknown): string | undefined {
  return typeof value === "string" && value.length > 0 ? value : undefined;
}

function toSurfaceRef(
  continuation: {
    channelId: string;
    enterpriseId?: string;
    teamId?: string;
    threadTs: string;
  },
  recipientUserRef?: string,
): SurfaceRef {
  const teamRef = continuation.teamId ?? continuation.enterpriseId;
  const locationRef = teamRef ? `${teamRef}:${continuation.channelId}` : continuation.channelId;
  return {
    surface: "slack",
    locationRef,
    channelRef: continuation.channelId,
    threadRef: continuation.threadTs,
    ...(teamRef === undefined ? {} : { teamRef }),
    ...(continuation.teamId === undefined || !recipientUserRef
      ? {}
      : { recipient: { teamRef: continuation.teamId, userRef: recipientUserRef } }),
  };
}

function slackTimestamp(eventTime: number | undefined, ts: string): string {
  const seconds = eventTime ?? Number(ts.split(".")[0]);
  return Number.isFinite(seconds)
    ? new Date(seconds * 1_000).toISOString()
    : new Date(0).toISOString();
}

function toRetry(retry: { num: number; reason?: string } | undefined): { retry?: DeliveryRetry } {
  if (retry === undefined) return {};
  return {
    retry: {
      attempt: retry.num,
      ...(retry.reason === undefined ? {} : { reason: retry.reason }),
    },
  };
}

function unsupported(
  nativeType: string,
  nativePayload: unknown,
  retry: { retry?: DeliveryRetry },
): SurfaceEvent {
  return { type: "unsupported", surface: "slack", nativeType, nativePayload, ...retry };
}
