/**
 * Convert a curated subset of a REST OpenAPI 3.x spec into tool-manifest
 * entries for a ProviderDef — the path for connectors that have no MCP
 * server.
 *
 *   pnpm --filter @trema/connectors openapi-to-manifest -- <spec> --list
 *   pnpm --filter @trema/connectors openapi-to-manifest -- <spec> --curation <file> [--format json|ts] [--out <file>]
 *
 * <spec> is a local JSON/YAML file or an http(s) URL. `--list` prints every
 * operation so a curator can author the curation file (JSON or YAML,
 * validated by manifestCurationSchema). The default output is JSON;
 * `--format ts` prints a `toolManifest` array ready to paste into a
 * provider definition file.
 */
import { readFile, writeFile } from "node:fs/promises";
import process from "node:process";

import { parse as parseYaml } from "yaml";

import {
  listOperations,
  type ManifestCurationInput,
  manifestCurationSchema,
  OpenApiConversionError,
  openApiSpecToToolManifest,
  parseOpenApiDocument,
  type ToolDefinition,
} from "#/index.js";

interface CliOptions {
  spec: string;
  curation?: string;
  list: boolean;
  format: "json" | "ts";
  out?: string;
}

function parseArgs(argv: string[]): CliOptions {
  const positional: string[] = [];
  const options: Omit<CliOptions, "spec"> = { list: false, format: "json" };

  for (let index = 0; index < argv.length; index += 1) {
    const argument = argv[index];
    switch (argument) {
      // pnpm forwards the `--` separator from `pnpm run … -- <args>`.
      case "--":
        break;
      case "--list":
        options.list = true;
        break;
      case "--curation":
      case "--format":
      case "--out": {
        const value = argv[index + 1];
        if (value === undefined) throw new Error(`${argument} requires a value`);
        index += 1;
        if (argument === "--curation") options.curation = value;
        else if (argument === "--out") options.out = value;
        else if (value === "json" || value === "ts") options.format = value;
        else throw new Error(`--format must be 'json' or 'ts', got '${value}'`);
        break;
      }
      default:
        if (argument?.startsWith("--")) throw new Error(`Unknown option '${argument}'`);
        if (argument !== undefined) positional.push(argument);
    }
  }

  const spec = positional[0];
  if (spec === undefined || positional.length !== 1) {
    throw new Error(
      "Usage: openapi-to-manifest <spec-file-or-url> (--list | --curation <file>) [--format json|ts] [--out <file>]",
    );
  }
  if (!options.list && options.curation === undefined) {
    throw new Error("Pass --curation <file> to convert, or --list to inspect the spec");
  }
  return { spec, ...options };
}

async function loadText(source: string): Promise<string> {
  if (source.startsWith("http://") || source.startsWith("https://")) {
    const response = await fetch(source);
    if (!response.ok) throw new Error(`Fetching ${source} failed: HTTP ${response.status}`);
    return await response.text();
  }
  return await readFile(source, "utf8");
}

async function loadCuration(source: string): Promise<ManifestCurationInput> {
  const text = await loadText(source);
  const raw: unknown = text.trimStart().startsWith("{") ? JSON.parse(text) : parseYaml(text);
  return manifestCurationSchema.parse(raw) satisfies ManifestCurationInput;
}

function renderTs(tools: ToolDefinition[]): string {
  const body = JSON.stringify(tools, null, 2)
    // Quoted keys → bare identifiers, matching the hand-written provider files.
    .replace(/^(\s*)"([A-Za-z_][A-Za-z0-9_]*)":/gm, "$1$2:");
  return `// Generated by openapi-to-manifest — review before committing: trim\n// descriptions, drop parameters the model does not need, and check\n// sensitivity classes.\ntoolManifest: ${body},\n`;
}

async function main(): Promise<void> {
  const options = parseArgs(process.argv.slice(2));
  const document = parseOpenApiDocument(await loadText(options.spec));

  if (options.list) {
    for (const operation of listOperations(document)) {
      const deprecated = operation.deprecated ? " [deprecated]" : "";
      const id = operation.operationId ?? "(no operationId)";
      const summary = operation.summary === undefined ? "" : ` — ${operation.summary}`;
      process.stdout.write(
        `${operation.method.padEnd(6)} ${operation.path}  ${id}${deprecated}${summary}\n`,
      );
    }
    return;
  }

  if (options.curation === undefined) throw new Error("--curation is required");
  const curation = await loadCuration(options.curation);
  const { tools, warnings } = openApiSpecToToolManifest(document, curation);

  for (const warning of warnings) process.stderr.write(`warning: ${warning}\n`);

  const output = options.format === "ts" ? renderTs(tools) : `${JSON.stringify(tools, null, 2)}\n`;
  if (options.out === undefined) {
    process.stdout.write(output);
  } else {
    await writeFile(options.out, output, "utf8");
    process.stderr.write(`Wrote ${tools.length} tools to ${options.out}\n`);
  }
}

main().catch((error: unknown) => {
  if (error instanceof OpenApiConversionError) {
    process.stderr.write(`${error.message}\n`);
  } else {
    process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`);
  }
  process.exitCode = 1;
});
