import type { ProviderDefInput } from "#connectors/schema.js";

export const githubProvider = {
  key: "github",
  trusted: true,
  displayName: "GitHub",
  description:
    "A curated set of tools for repositories, issues, pull requests, and their comments over the GitHub REST API.",
  logoUrl: "/connector-logos/github.svg",
  categories: ["developer-tools"],
  docsUrl: "https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/authorizing-oauth-apps",
  authMode: "oauth2_code",
  auth: {
    authorizationUrl: "https://github.com/login/oauth/authorize",
    tokenUrl: "https://github.com/login/oauth/access_token",
    defaultScopes: ["read:user", "repo"],
    // Full GitHub OAuth scope vocabulary (verbatim from the vendored Nango
    // scope catalog, packages/providers/providers.scopes.yaml, key `github`).
    availableScopes: [
      "admin:gpg_key",
      "admin:org",
      "admin:org_hook",
      "admin:public_key",
      "admin:repo_hook",
      "codespace",
      "delete_repo",
      "delete:packages",
      "gist",
      "notifications",
      "project",
      "public_repo",
      "read:audit_log",
      "read:gpg_key",
      "read:org",
      "read:packages",
      "read:project",
      "read:public_key",
      "read:repo_hook",
      "read:user",
      "repo",
      "repo_deployment",
      "repo:invite",
      "repo:status",
      "security_events",
      "user",
      "user:email",
      "user:follow",
      "workflow",
      "write:gpg_key",
      "write:org",
      "write:packages",
      "write:public_key",
      "write:repo_hook",
    ],
    // GitHub OAuth apps do not support PKCE.
    pkce: false,
  },
  configFields: {},
  credentialFields: {},
  transport: {
    type: "rest",
    baseUrl: "https://api.github.com",
    openApiSpecUrl:
      "https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.json",
    verification: { method: "GET", endpoints: ["/user"] },
  },
  toolManifest: [
    {
      name: "search_issues",
      description: "Search issues and pull requests visible to the connected GitHub account.",
      method: "GET",
      path: "/search/issues",
      paramsSchema: {
        type: "object",
        properties: { q: { type: "string" } },
        required: ["q"],
      },
    },
    {
      name: "get_issue",
      description: "Get one issue from a GitHub repository.",
      method: "GET",
      path: "/repos/{owner}/{repo}/issues/{issueNumber}",
      paramsSchema: {
        type: "object",
        properties: {
          owner: { type: "string" },
          repo: { type: "string" },
          issueNumber: { type: "integer" },
        },
        required: ["owner", "repo", "issueNumber"],
      },
    },
    {
      name: "create_issue_comment",
      description: "Add a comment to an issue or pull request in a GitHub repository.",
      method: "POST",
      path: "/repos/{owner}/{repo}/issues/{issueNumber}/comments",
      paramsSchema: {
        type: "object",
        properties: {
          owner: { type: "string" },
          repo: { type: "string" },
          issueNumber: { type: "integer" },
          body: { type: "string" },
        },
        required: ["owner", "repo", "issueNumber", "body"],
      },
    },
    {
      name: "get_pull_request",
      description: "Get one pull request from a GitHub repository.",
      method: "GET",
      path: "/repos/{owner}/{repo}/pulls/{pullNumber}",
      paramsSchema: {
        type: "object",
        properties: {
          owner: { type: "string" },
          repo: { type: "string" },
          pullNumber: { type: "integer" },
        },
        required: ["owner", "repo", "pullNumber"],
      },
    },
    {
      name: "list_pull_requests",
      description:
        "List pull requests in a GitHub repository, filterable by state, head, and base.",
      method: "GET",
      path: "/repos/{owner}/{repo}/pulls",
      paramsSchema: {
        type: "object",
        properties: {
          owner: { type: "string" },
          repo: { type: "string" },
          state: { type: "string", enum: ["open", "closed", "all"] },
          head: {
            type: "string",
            description: "Filter by head branch as user:ref-name or org:ref-name.",
          },
          base: { type: "string", description: "Filter by base branch name." },
          sort: { type: "string", enum: ["created", "updated", "popularity", "long-running"] },
          direction: { type: "string", enum: ["asc", "desc"] },
          per_page: { type: "integer" },
        },
        required: ["owner", "repo"],
      },
    },
    {
      name: "create_issue",
      description: "Open a new issue in a GitHub repository.",
      method: "POST",
      path: "/repos/{owner}/{repo}/issues",
      paramsSchema: {
        type: "object",
        properties: {
          owner: { type: "string" },
          repo: { type: "string" },
          title: { type: "string" },
          body: { type: "string" },
          assignees: {
            type: "array",
            items: { type: "string" },
            description: "Logins of users to assign.",
          },
          labels: {
            type: "array",
            items: { type: "string" },
            description: "Label names to apply.",
          },
        },
        required: ["owner", "repo", "title"],
      },
    },
    {
      name: "update_issue",
      description: "Update a GitHub issue's title, body, state, labels, or assignees.",
      method: "PATCH",
      path: "/repos/{owner}/{repo}/issues/{issueNumber}",
      paramsSchema: {
        type: "object",
        properties: {
          owner: { type: "string" },
          repo: { type: "string" },
          issueNumber: { type: "integer" },
          title: { type: "string" },
          body: { type: "string" },
          state: { type: "string", enum: ["open", "closed"] },
          state_reason: {
            type: "string",
            enum: ["completed", "not_planned", "duplicate", "reopened"],
          },
          labels: {
            type: "array",
            items: { type: "string" },
            description: "Replaces the issue's labels; send [] to clear.",
          },
          assignees: {
            type: "array",
            items: { type: "string" },
            description: "Replaces the issue's assignees; send [] to clear.",
          },
        },
        required: ["owner", "repo", "issueNumber"],
      },
    },
    {
      name: "list_issue_comments",
      description: "List the comments on a GitHub issue or pull request.",
      method: "GET",
      path: "/repos/{owner}/{repo}/issues/{issueNumber}/comments",
      paramsSchema: {
        type: "object",
        properties: {
          owner: { type: "string" },
          repo: { type: "string" },
          issueNumber: { type: "integer" },
          since: { type: "string", description: "Only comments updated after this ISO 8601 time." },
          per_page: { type: "integer" },
        },
        required: ["owner", "repo", "issueNumber"],
      },
    },
    {
      name: "get_repository",
      description: "Get metadata for one GitHub repository.",
      method: "GET",
      path: "/repos/{owner}/{repo}",
      paramsSchema: {
        type: "object",
        properties: {
          owner: { type: "string" },
          repo: { type: "string" },
        },
        required: ["owner", "repo"],
      },
    },
    {
      name: "list_repositories",
      description: "List repositories the connected GitHub account can access.",
      method: "GET",
      path: "/user/repos",
      paramsSchema: {
        type: "object",
        properties: {
          visibility: { type: "string", enum: ["all", "public", "private"] },
          affiliation: {
            type: "string",
            description: "Comma-separated: owner, collaborator, organization_member.",
          },
          sort: { type: "string", enum: ["created", "updated", "pushed", "full_name"] },
          per_page: { type: "integer" },
        },
      },
    },
    {
      name: "get_file_contents",
      description: "Get the contents of a file or directory in a GitHub repository at a path.",
      method: "GET",
      path: "/repos/{owner}/{repo}/contents/{path}",
      paramsSchema: {
        type: "object",
        properties: {
          owner: { type: "string" },
          repo: { type: "string" },
          path: { type: "string", description: "Path to a file or directory within the repo." },
          ref: {
            type: "string",
            description: "Commit, branch, or tag. Default: the default branch.",
          },
        },
        required: ["owner", "repo", "path"],
      },
    },
    {
      name: "list_commits",
      description: "List commits on a GitHub repository, filterable by branch, path, or author.",
      method: "GET",
      path: "/repos/{owner}/{repo}/commits",
      paramsSchema: {
        type: "object",
        properties: {
          owner: { type: "string" },
          repo: { type: "string" },
          sha: { type: "string", description: "SHA or branch to start listing from." },
          path: { type: "string", description: "Only commits touching this file path." },
          author: { type: "string", description: "Filter by commit author (login or email)." },
          since: { type: "string", description: "Only commits after this ISO 8601 time." },
          until: { type: "string", description: "Only commits before this ISO 8601 time." },
          per_page: { type: "integer" },
        },
        required: ["owner", "repo"],
      },
    },
    {
      name: "search_repositories",
      description: "Search GitHub repositories with GitHub's repository search syntax.",
      method: "GET",
      path: "/search/repositories",
      paramsSchema: {
        type: "object",
        properties: {
          q: { type: "string" },
          sort: { type: "string", enum: ["stars", "forks", "help-wanted-issues", "updated"] },
          order: { type: "string", enum: ["desc", "asc"] },
          per_page: { type: "integer" },
        },
        required: ["q"],
      },
    },
    {
      name: "search_code",
      description: "Search for code across GitHub repositories with GitHub's code search syntax.",
      method: "GET",
      path: "/search/code",
      paramsSchema: {
        type: "object",
        properties: {
          q: { type: "string" },
          per_page: { type: "integer" },
        },
        required: ["q"],
      },
    },
    {
      name: "list_pull_request_files",
      description: "List the files changed in a GitHub pull request.",
      method: "GET",
      path: "/repos/{owner}/{repo}/pulls/{pullNumber}/files",
      paramsSchema: {
        type: "object",
        properties: {
          owner: { type: "string" },
          repo: { type: "string" },
          pullNumber: { type: "integer" },
          per_page: { type: "integer" },
        },
        required: ["owner", "repo", "pullNumber"],
      },
    },
    {
      name: "create_pull_request_comment",
      description: "Add a review comment on a specific line of a GitHub pull request's diff.",
      method: "POST",
      path: "/repos/{owner}/{repo}/pulls/{pullNumber}/comments",
      paramsSchema: {
        type: "object",
        properties: {
          owner: { type: "string" },
          repo: { type: "string" },
          pullNumber: { type: "integer" },
          body: { type: "string", description: "The text of the review comment." },
          commit_id: { type: "string", description: "SHA of the commit to comment on." },
          path: { type: "string", description: "Relative path of the file to comment on." },
          line: {
            type: "integer",
            description: "Line in the diff the comment applies to (last line for a range).",
          },
          side: { type: "string", enum: ["LEFT", "RIGHT"] },
          start_line: {
            type: "integer",
            description: "First line of a multi-line comment range.",
          },
          subject_type: { type: "string", enum: ["line", "file"] },
        },
        required: ["owner", "repo", "pullNumber", "body", "commit_id", "path"],
      },
    },
  ],
  memberConnectable: true,
} satisfies ProviderDefInput;
