import type { ProviderDefInput } from "#connectors/schema.js";

export const hubspotProvider = {
  key: "hubspot",
  displayName: "HubSpot",
  description:
    "A curated set of tools to search and manage contacts, companies, and deals over the HubSpot CRM REST API.",
  logoUrl: "/connector-logos/hubspot.svg",
  categories: ["CRM"],
  docsUrl: "https://developers.hubspot.com/docs/api/oauth-quickstart-guide",
  authMode: "oauth2_code",
  auth: {
    authorizationUrl: "https://app.hubspot.com/oauth/authorize",
    tokenUrl: "https://api.hubapi.com/oauth/v1/token",
    defaultScopes: [
      "crm.objects.contacts.read",
      "crm.objects.contacts.write",
      "crm.objects.companies.read",
      // companies.write powers create_company; deals.write powers create_deal
      // and update_deal; owners.read powers list_owners. All are present in
      // availableScopes below. Note creation is covered by contacts.write.
      "crm.objects.companies.write",
      "crm.objects.deals.read",
      "crm.objects.deals.write",
      "crm.objects.owners.read",
    ],
    // Full HubSpot OAuth scope vocabulary (verbatim from the vendored Nango
    // scope catalog, packages/providers/providers.scopes.yaml, key `hubspot`).
    availableScopes: [
      "account-info.security.read",
      "accounting",
      "actions",
      "analytics.behavioral_events.send",
      "automation",
      "automation.sequences.enrollments.write",
      "automation.sequences.read",
      "behavioral_events.event_definitions.read_write",
      "business_units.view.read",
      "business-intelligence",
      "cms.domains.read",
      "cms.domains.write",
      "cms.functions.read",
      "cms.functions.write",
      "cms.knowledge_base.articles.publish",
      "cms.knowledge_base.articles.read",
      "cms.knowledge_base.articles.write",
      "cms.knowledge_base.settings.read",
      "cms.knowledge_base.settings.write",
      "cms.membership.access_groups.read",
      "cms.membership.access_groups.write",
      "collector.graphql_query.execute",
      "collector.graphql_schema.read",
      "communication_preferences.read",
      "communication_preferences.read_write",
      "communication_preferences.statuses.batch.read",
      "communication_preferences.statuses.batch.write",
      "communication_preferences.write",
      "content",
      "conversations.custom_channels.read",
      "conversations.custom_channels.write",
      "conversations.read",
      "conversations.visitor_identification.tokens.create",
      "conversations.write",
      "crm.dealsplits.read_write",
      "crm.export",
      "crm.import",
      "crm.lists.read",
      "crm.lists.write",
      "crm.objects.appointments.read",
      "crm.objects.appointments.sensitive.read",
      "crm.objects.appointments.sensitive.write",
      "crm.objects.appointments.write",
      "crm.objects.carts.read",
      "crm.objects.carts.write",
      "crm.objects.commercepayments.read",
      "crm.objects.companies.highly_sensitive.read",
      "crm.objects.companies.highly_sensitive.write",
      "crm.objects.companies.read",
      "crm.objects.companies.sensitive.read",
      "crm.objects.companies.sensitive.write",
      "crm.objects.companies.write",
      "crm.objects.contacts.highly_sensitive.read",
      "crm.objects.contacts.highly_sensitive.write",
      "crm.objects.contacts.read",
      "crm.objects.contacts.sensitive.read",
      "crm.objects.contacts.sensitive.write",
      "crm.objects.contacts.write",
      "crm.objects.courses.read",
      "crm.objects.courses.write",
      "crm.objects.custom.highly_sensitive.read",
      "crm.objects.custom.highly_sensitive.write",
      "crm.objects.custom.read",
      "crm.objects.custom.sensitive.read",
      "crm.objects.custom.sensitive.write",
      "crm.objects.custom.write",
      "crm.objects.deals.highly_sensitive.read",
      "crm.objects.deals.highly_sensitive.write",
      "crm.objects.deals.read",
      "crm.objects.deals.sensitive.read",
      "crm.objects.deals.sensitive.write",
      "crm.objects.deals.write",
      "crm.objects.feedback_submission.read",
      "crm.objects.goals.read",
      "crm.objects.invoices.read",
      "crm.objects.leads.read",
      "crm.objects.leads.write",
      "crm.objects.line_items.read",
      "crm.objects.line_items.write",
      "crm.objects.listings.read",
      "crm.objects.listings.write",
      "crm.objects.marketing_events.read",
      "crm.objects.marketing_events.write",
      "crm.objects.orders.read",
      "crm.objects.orders.write",
      "crm.objects.owners.read",
      "crm.objects.partner-clients.read",
      "crm.objects.partner-clients.write",
      "crm.objects.partner-services.read",
      "crm.objects.partner-services.write",
      "crm.objects.projects.highly_sensitive.read",
      "crm.objects.projects.highly_sensitive.write",
      "crm.objects.projects.read",
      "crm.objects.projects.sensitive.read",
      "crm.objects.projects.sensitive.write",
      "crm.objects.projects.write",
      "crm.objects.quotes.read",
      "crm.objects.quotes.write",
      "crm.objects.services.read",
      "crm.objects.services.write",
      "crm.objects.subscriptions.read",
      "crm.objects.users.read",
      "crm.objects.users.write",
      "crm.pipelines.orders.read",
      "crm.pipelines.orders.write",
      "crm.schemas.appointments.read",
      "crm.schemas.appointments.write",
      "crm.schemas.carts.read",
      "crm.schemas.carts.write",
      "crm.schemas.commercepayments.read",
      "crm.schemas.companies.read",
      "crm.schemas.companies.write",
      "crm.schemas.contacts.read",
      "crm.schemas.contacts.write",
      "crm.schemas.custom.read",
      "crm.schemas.deals.read",
      "crm.schemas.deals.write",
      "crm.schemas.invoices.read",
      "crm.schemas.invoices.write",
      "crm.schemas.line_items.read",
      "crm.schemas.listings.read",
      "crm.schemas.listings.write",
      "crm.schemas.orders.read",
      "crm.schemas.orders.write",
      "crm.schemas.projects.read",
      "crm.schemas.projects.write",
      "crm.schemas.quotes.read",
      "crm.schemas.services.read",
      "crm.schemas.services.write",
      "crm.schemas.subscriptions.read",
      "crm.schemas.subscriptions.write",
      "ctas.read",
      "e-commerce",
      "external_integrations.forms.access",
      "files",
      "files.ui_hidden.read",
      "forms",
      "forms-uploaded-files",
      "hubdb",
      "integration-sync",
      "marketing-email",
      "marketing.campaigns.read",
      "marketing.campaigns.revenue.read",
      "marketing.campaigns.write",
      "media_bridge.read",
      "media_bridge.write",
      "oauth",
      "sales-email-read",
      "scheduler.meetings.meeting-link.read",
      "settings.billing.write",
      "settings.currencies.read",
      "settings.currencies.write",
      "settings.users.read",
      "settings.users.team.write",
      "settings.users.teams.read",
      "settings.users.write",
      "social",
      "tax_rates.read",
      "tickets",
      "tickets.highly_sensitive",
      "tickets.sensitive",
      "timeline",
      "transactional-email",
    ],
    // The token response's Hub ID is the stable ID of the selected account.
    accountIdentityFields: ["hub_id"],
  },
  configFields: {},
  credentialFields: {},
  transport: {
    type: "rest",
    baseUrl: "https://api.hubapi.com",
    // No openApiSpecUrl: HubSpot ships per-API specs through its catalog rather
    // than one stable raw CRM-objects spec URL, so this manifest is hand-curated.
    retry: { remainingHeader: "x-hubspot-ratelimit-remaining" },
    verification: { method: "GET", endpoints: ["/oauth/v1/access-tokens/current"] },
  },
  toolManifest: [
    {
      name: "search_contacts",
      // POST transport, read semantics: HubSpot's search endpoint mutates nothing.
      description: "Search HubSpot contacts by property filters or free-text query.",
      method: "POST",
      path: "/crm/v3/objects/contacts/search",
      paramsSchema: {
        type: "object",
        properties: {
          query: { type: "string", description: "Free-text search across default properties." },
          filterGroups: {
            type: "array",
            description: "HubSpot filter groups for property matches.",
          },
          properties: { type: "array", items: { type: "string" } },
          limit: { type: "integer" },
          after: { type: "string", description: "Paging cursor from a previous search." },
        },
      },
      sensitivity: "read",
    },
    {
      name: "get_contact",
      description: "Get one HubSpot contact by id.",
      method: "GET",
      path: "/crm/v3/objects/contacts/{contactId}",
      paramsSchema: {
        type: "object",
        properties: {
          contactId: { type: "string" },
          properties: { type: "string", description: "Comma-separated property names to return." },
        },
        required: ["contactId"],
      },
      sensitivity: "read",
    },
    {
      name: "create_contact",
      description: "Create a HubSpot contact.",
      method: "POST",
      path: "/crm/v3/objects/contacts",
      paramsSchema: {
        type: "object",
        properties: {
          properties: {
            type: "object",
            description: "Contact properties, e.g. email, firstname, lastname, company.",
          },
        },
        required: ["properties"],
      },
      sensitivity: "write",
    },
    {
      name: "update_contact",
      description: "Update properties of a HubSpot contact.",
      method: "PATCH",
      path: "/crm/v3/objects/contacts/{contactId}",
      paramsSchema: {
        type: "object",
        properties: {
          contactId: { type: "string" },
          properties: { type: "object" },
        },
        required: ["contactId", "properties"],
      },
      sensitivity: "write",
    },
    {
      name: "search_deals",
      description: "Search HubSpot deals by property filters or free-text query.",
      method: "POST",
      path: "/crm/v3/objects/deals/search",
      paramsSchema: {
        type: "object",
        properties: {
          query: { type: "string" },
          filterGroups: { type: "array" },
          properties: { type: "array", items: { type: "string" } },
          limit: { type: "integer" },
          after: { type: "string" },
        },
      },
      sensitivity: "read",
    },
    {
      name: "search_companies",
      // POST transport, read semantics: HubSpot's search endpoint mutates nothing.
      description: "Search HubSpot companies by property filters or free-text query.",
      method: "POST",
      path: "/crm/v3/objects/companies/search",
      paramsSchema: {
        type: "object",
        properties: {
          query: { type: "string", description: "Free-text search across default properties." },
          filterGroups: {
            type: "array",
            description: "HubSpot filter groups for property matches.",
          },
          properties: { type: "array", items: { type: "string" } },
          limit: { type: "integer" },
          after: { type: "string", description: "Paging cursor from a previous search." },
        },
      },
      sensitivity: "read",
    },
    {
      name: "get_company",
      description: "Get one HubSpot company by id.",
      method: "GET",
      path: "/crm/v3/objects/companies/{companyId}",
      paramsSchema: {
        type: "object",
        properties: {
          companyId: { type: "string" },
          properties: { type: "string", description: "Comma-separated property names to return." },
        },
        required: ["companyId"],
      },
      sensitivity: "read",
    },
    {
      name: "create_company",
      description: "Create a HubSpot company.",
      method: "POST",
      path: "/crm/v3/objects/companies",
      paramsSchema: {
        type: "object",
        properties: {
          properties: {
            type: "object",
            description: "Company properties, e.g. name, domain, industry.",
          },
        },
        required: ["properties"],
      },
      sensitivity: "write",
    },
    {
      name: "get_deal",
      description: "Get one HubSpot deal by id.",
      method: "GET",
      path: "/crm/v3/objects/deals/{dealId}",
      paramsSchema: {
        type: "object",
        properties: {
          dealId: { type: "string" },
          properties: { type: "string", description: "Comma-separated property names to return." },
        },
        required: ["dealId"],
      },
      sensitivity: "read",
    },
    {
      name: "create_deal",
      description: "Create a HubSpot deal.",
      method: "POST",
      path: "/crm/v3/objects/deals",
      paramsSchema: {
        type: "object",
        properties: {
          properties: {
            type: "object",
            description: "Deal properties, e.g. dealname, amount, dealstage, pipeline.",
          },
        },
        required: ["properties"],
      },
      sensitivity: "write",
    },
    {
      name: "update_deal",
      description: "Update properties of a HubSpot deal.",
      method: "PATCH",
      path: "/crm/v3/objects/deals/{dealId}",
      paramsSchema: {
        type: "object",
        properties: {
          dealId: { type: "string" },
          properties: { type: "object" },
        },
        required: ["dealId", "properties"],
      },
      sensitivity: "write",
    },
    {
      name: "create_note",
      description: "Create a HubSpot note, optionally associated with CRM records.",
      method: "POST",
      path: "/crm/v3/objects/notes",
      paramsSchema: {
        type: "object",
        properties: {
          properties: {
            type: "object",
            description: "Note properties: hs_note_body (the text) and hs_timestamp.",
          },
          associations: {
            type: "array",
            description: "Associations to contacts, companies, or deals for this note.",
          },
        },
        required: ["properties"],
      },
      sensitivity: "write",
    },
    {
      name: "list_owners",
      description: "List HubSpot owners (users who can be assigned records), optionally by email.",
      method: "GET",
      path: "/crm/v3/owners",
      paramsSchema: {
        type: "object",
        properties: {
          email: { type: "string", description: "Filter to the owner with this email." },
          limit: { type: "integer" },
          after: { type: "string", description: "Paging cursor from a previous page." },
        },
      },
      sensitivity: "read",
    },
    {
      name: "get_associations",
      description:
        "List the records of one type associated with a HubSpot record, e.g. the contacts on a deal.",
      method: "GET",
      path: "/crm/v4/objects/{objectType}/{objectId}/associations/{toObjectType}",
      paramsSchema: {
        type: "object",
        properties: {
          objectType: { type: "string", description: "Source object type, e.g. deals." },
          objectId: { type: "string", description: "Source record id." },
          toObjectType: { type: "string", description: "Associated object type, e.g. contacts." },
          after: { type: "string", description: "Paging cursor from a previous page." },
        },
        required: ["objectType", "objectId", "toObjectType"],
      },
      sensitivity: "read",
    },
  ],
  memberConnectable: false,
} satisfies ProviderDefInput;
