import type { ProviderDefInput } from "#/schema.js";

// Miro's MCP server is a deliberate abstraction rather than a full REST API
// mirror, so the REST API supplies the complete board-management integration.
export const miroProvider = {
  key: "miro",
  displayName: "Miro",
  description: "Read, create, and organize Miro boards and board items over the REST API.",
  logoUrl: "/connector-logos/miro.svg",
  categories: ["design"],
  docsUrl: "https://developers.miro.com/docs/rest-api-reference-guide",
  authMode: "oauth2_code",
  auth: {
    authorizationUrl: "https://miro.com/oauth/authorize",
    tokenUrl: "https://api.miro.com/v1/oauth/token",
    defaultScopes: ["boards:read", "boards:write"],
    // Full Miro OAuth scope vocabulary (verbatim from Nango's scope catalog).
    availableScopes: [
      "auditlogs:read",
      "boards:export",
      "boards:read",
      "boards:write",
      "contentlogs:export",
      "identity:read",
      "identity:write",
      "microphone:listen",
      "organizations:cases:management",
      "organizations:groups:read",
      "organizations:groups:write",
      "organizations:read",
      "organizations:teams:read",
      "organizations:teams:write",
      "projects:read",
      "projects:write",
      "screen:record",
      "sessions:delete",
      "team:read",
      "team:write",
      "webcam:record",
    ],
    // Miro requires the client credentials in the token request parameters.
    tokenRequestAuthMethod: "body",
  },
  configFields: {},
  credentialFields: {},
  transport: {
    type: "rest",
    baseUrl: "https://api.miro.com",
    // Miro publishes a REST reference but no stable OpenAPI 3 document.
    verification: { method: "GET", endpoints: ["/v1/oauth-token"] },
  },
  toolManifest: [
    {
      name: "list_boards",
      description: "List boards accessible to the connected Miro user.",
      method: "GET",
      path: "/v2/boards",
      paramsSchema: {
        type: "object",
        properties: { limit: { type: "integer" }, cursor: { type: "string" } },
      },
      sensitivity: "read",
    },
    {
      name: "get_board",
      description: "Get a Miro board by id.",
      method: "GET",
      path: "/v2/boards/{boardId}",
      paramsSchema: {
        type: "object",
        properties: { boardId: { type: "string" } },
        required: ["boardId"],
      },
      sensitivity: "read",
    },
    {
      name: "create_board",
      description: "Create a new Miro board.",
      method: "POST",
      path: "/v2/boards",
      paramsSchema: {
        type: "object",
        properties: {
          name: { type: "string" },
          description: { type: "string" },
          projectId: { type: "string" },
          policy: { type: "object" },
        },
        required: ["name"],
      },
      sensitivity: "write",
    },
    {
      name: "update_board",
      description: "Update a Miro board's name, description, or sharing policy.",
      method: "PATCH",
      path: "/v2/boards/{boardId}",
      paramsSchema: {
        type: "object",
        properties: {
          boardId: { type: "string" },
          name: { type: "string" },
          description: { type: "string" },
          policy: { type: "object" },
        },
        required: ["boardId"],
      },
      sensitivity: "write",
    },
    {
      name: "list_board_items",
      description: "List items on a Miro board.",
      method: "GET",
      path: "/v2/boards/{boardId}/items",
      paramsSchema: {
        type: "object",
        properties: {
          boardId: { type: "string" },
          type: { type: "string" },
          limit: { type: "integer" },
          cursor: { type: "string" },
        },
        required: ["boardId"],
      },
      sensitivity: "read",
    },
    {
      name: "get_board_item",
      description: "Get one item on a Miro board.",
      method: "GET",
      path: "/v2/boards/{boardId}/items/{itemId}",
      paramsSchema: {
        type: "object",
        properties: { boardId: { type: "string" }, itemId: { type: "string" } },
        required: ["boardId", "itemId"],
      },
      sensitivity: "read",
    },
    {
      name: "create_sticky_note",
      description: "Add a sticky note to a Miro board.",
      method: "POST",
      path: "/v2/boards/{boardId}/sticky_notes",
      paramsSchema: {
        type: "object",
        properties: {
          boardId: { type: "string" },
          content: { type: "string" },
          shape: { type: "string" },
          style: { type: "object" },
          position: { type: "object" },
        },
        required: ["boardId", "content"],
      },
      sensitivity: "write",
    },
    {
      name: "create_shape",
      description: "Add a shape to a Miro board.",
      method: "POST",
      path: "/v2/boards/{boardId}/shapes",
      paramsSchema: {
        type: "object",
        properties: {
          boardId: { type: "string" },
          content: { type: "string" },
          shape: { type: "string" },
          style: { type: "object" },
          position: { type: "object" },
        },
        required: ["boardId", "content", "shape"],
      },
      sensitivity: "write",
    },
    {
      name: "delete_board_item",
      description: "Delete an item from a Miro board.",
      method: "DELETE",
      path: "/v2/boards/{boardId}/items/{itemId}",
      paramsSchema: {
        type: "object",
        properties: { boardId: { type: "string" }, itemId: { type: "string" } },
        required: ["boardId", "itemId"],
      },
      sensitivity: "destructive",
    },
  ],
  memberConnectable: true,
} satisfies ProviderDefInput;
