import type { ProviderDefInput } from "#connectors/schema.js";

export const slackProvider = {
  key: "slack",
  trusted: true,
  displayName: "Slack",
  description:
    "A curated set of tools to read channels and conversation history and post messages over the Slack Web API.",
  logoUrl: "/connector-logos/slack.svg",
  categories: ["communication"],
  docsUrl: "https://api.slack.com/authentication/oauth-v2",
  authMode: "oauth2_code",
  oauthActor: "app",
  auth: {
    authorizationUrl: "https://slack.com/oauth/v2/authorize",
    tokenUrl: "https://slack.com/api/oauth.v2.access",
    defaultScopes: [
      "app_mentions:read",
      "channels:read",
      "channels:history",
      "chat:write",
      "groups:read",
      "groups:history",
      "im:read",
      "im:history",
      "im:write",
      "mpim:read",
      "mpim:history",
      "users:read",
      "reactions:write",
      "channels:join",
    ],
    // Full Slack OAuth scope vocabulary (verbatim from the vendored Nango scope
    // catalog, packages/providers/providers.scopes.yaml, key `slack`).
    availableScopes: [
      "admin",
      "admin.analytics:read",
      "admin.app_activities:read",
      "admin.apps:read",
      "admin.apps:write",
      "admin.barriers:read",
      "admin.barriers:write",
      "admin.conversations:read",
      "admin.conversations:write",
      "admin.invites:read",
      "admin.invites:write",
      "admin.roles:read",
      "admin.roles:write",
      "admin.teams:read",
      "admin.teams:write",
      "admin.usergroups:read",
      "admin.usergroups:write",
      "admin.users:read",
      "admin.users:write",
      "admin.workflows:read",
      "admin.workflows:write",
      "app_configurations:read",
      "app_configurations:write",
      "app_mentions:read",
      "apps.requests:write",
      "assistant:write",
      "auditlogs:read",
      "authorizations:read",
      "bookmarks:read",
      "bookmarks:write",
      "bot",
      "calls:read",
      "calls:write",
      "canvases:read",
      "canvases:write",
      "channels:history",
      "channels:join",
      "channels:manage",
      "channels:read",
      "channels:write",
      "channels:write.invites",
      "channels:write.topic",
      "chat:write",
      "chat:write:bot",
      "chat:write:user",
      "chat:write.customize",
      "chat:write.public",
      "client",
      "commands",
      "connections:write",
      "conversations.connect:manage",
      "conversations.connect:read",
      "conversations.connect:write",
      "datastore:read",
      "datastore:write",
      "dnd:read",
      "dnd:write",
      "email",
      "emoji:read",
      "files:read",
      "files:write",
      "files:write:user",
      "groups:history",
      "groups:read",
      "groups:write",
      "groups:write.invites",
      "groups:write.topic",
      "hosting:read",
      "hosting:write",
      "identify",
      "identity.avatar",
      "identity.basic",
      "identity.email",
      "identity.team",
      "im:history",
      "im:read",
      "im:write",
      "im:write.topic",
      "incoming-webhook",
      "links:read",
      "links:write",
      "links.embed:write",
      "lists:read",
      "metadata.message:read",
      "mpim:history",
      "mpim:read",
      "mpim:write",
      "mpim:write.invites",
      "mpim:write.topic",
      "none",
      "openid",
      "pins:read",
      "pins:write",
      "post",
      "profile",
      "reactions:read",
      "reactions:write",
      "read",
      "reminders:read",
      "reminders:write",
      "remote_files:read",
      "remote_files:share",
      "remote_files:write",
      "search:read",
      "search:read.enterprise",
      "search:read.im",
      "search:read.mpim",
      "search:read.private",
      "search:read.public",
      "stars:read",
      "stars:write",
      "team:read",
      "team.billing:read",
      "team.preferences:read",
      "tokens.basic",
      "triggers:read",
      "triggers:write",
      "usergroups:read",
      "usergroups:write",
      "users:read",
      "users:read.email",
      "users:write",
      "users.profile:read",
      "users.profile:write",
      "workflow.steps:execute",
    ],
    scopeSeparator: ",",
    // apps.uninstall rejects granular bot tokens. Request a minimally scoped
    // user token alongside the bot token so Trema can remove the complete app
    // installation rather than revoking only one rotating token.
    authorizationParams: { user_scope: "users:read" },
    tokenRequestAuthMethod: "body",
    // Slack's v2 OAuth flow does not support PKCE.
    pkce: false,
    // These non-secret fields make an installation inspectable and allow an
    // inbound request to resolve its workspace without decrypting credentials.
    tokenResponseMetadata: [
      "team.name",
      "enterprise.id",
      "enterprise.name",
      "bot_user_id",
      "app_id",
      "authed_user.id",
      "is_enterprise_install",
    ],
    accountIdentityFields: ["team.id"],
  },
  configFields: {},
  credentialFields: {},
  transport: {
    type: "rest",
    baseUrl: "https://slack.com/api",
    // Slack publishes its Web API spec as Swagger 2.0; our openapi-to-manifest
    // converter needs OpenAPI 3.x, so this link is provenance only, not fed to
    // the converter as-is.
    openApiSpecUrl:
      "https://raw.githubusercontent.com/slackapi/slack-api-specs/master/web-api/slack_web_openapi_v2.json",
    retry: { afterHeaders: ["retry-after"] },
    verification: { method: "GET", endpoints: ["/auth.test"] },
  },
  toolManifest: [
    {
      name: "list_channels",
      description: "List channels in the connected Slack workspace.",
      method: "GET",
      path: "/conversations.list",
      paramsSchema: {
        type: "object",
        properties: {
          types: {
            type: "string",
            description: "Comma-separated channel types: public_channel, private_channel.",
          },
          cursor: { type: "string" },
          limit: { type: "integer" },
        },
      },
    },
    {
      name: "get_channel_history",
      description: "Read recent messages from a Slack channel.",
      method: "GET",
      path: "/conversations.history",
      paramsSchema: {
        type: "object",
        properties: {
          channel: { type: "string", description: "Channel id, e.g. C0123456789." },
          cursor: { type: "string" },
          limit: { type: "integer" },
          oldest: { type: "string", description: "Only messages after this Unix timestamp." },
        },
        required: ["channel"],
      },
    },
    {
      name: "post_message",
      description: "Post a message to a Slack channel or thread.",
      method: "POST",
      path: "/chat.postMessage",
      paramsSchema: {
        type: "object",
        properties: {
          channel: { type: "string", description: "Channel id to post into." },
          text: { type: "string" },
          thread_ts: {
            type: "string",
            description: "Timestamp of a parent message to reply in its thread.",
          },
        },
        required: ["channel", "text"],
      },
    },
    {
      name: "get_user",
      description: "Look up a Slack user by id.",
      method: "GET",
      path: "/users.info",
      paramsSchema: {
        type: "object",
        properties: { user: { type: "string", description: "User id, e.g. U0123456789." } },
        required: ["user"],
      },
    },
    {
      name: "get_thread_replies",
      description: "Read the replies in a Slack message thread.",
      method: "GET",
      path: "/conversations.replies",
      paramsSchema: {
        type: "object",
        properties: {
          channel: { type: "string", description: "Channel id the thread is in." },
          ts: { type: "string", description: "Timestamp of the thread's parent message." },
          cursor: { type: "string" },
          limit: { type: "integer" },
        },
        required: ["channel", "ts"],
      },
    },
    {
      name: "list_users",
      description: "List the members of the connected Slack workspace.",
      method: "GET",
      path: "/users.list",
      paramsSchema: {
        type: "object",
        properties: {
          cursor: { type: "string" },
          limit: { type: "integer" },
        },
      },
    },
    {
      name: "get_channel_info",
      description: "Get metadata about a Slack channel.",
      method: "GET",
      path: "/conversations.info",
      paramsSchema: {
        type: "object",
        properties: { channel: { type: "string", description: "Channel id, e.g. C0123456789." } },
        required: ["channel"],
      },
    },
    {
      name: "update_message",
      description: "Edit the text of a message the connected app posted to a Slack channel.",
      method: "POST",
      path: "/chat.update",
      paramsSchema: {
        type: "object",
        properties: {
          channel: { type: "string", description: "Channel id the message is in." },
          ts: { type: "string", description: "Timestamp of the message to edit." },
          text: { type: "string" },
        },
        required: ["channel", "ts", "text"],
      },
    },
    {
      name: "delete_message",
      description: "Delete a message the connected app posted to a Slack channel.",
      method: "POST",
      path: "/chat.delete",
      paramsSchema: {
        type: "object",
        properties: {
          channel: { type: "string", description: "Channel id the message is in." },
          ts: { type: "string", description: "Timestamp of the message to delete." },
        },
        required: ["channel", "ts"],
      },
    },
    {
      name: "add_reaction",
      description: "Add an emoji reaction to a Slack message.",
      method: "POST",
      path: "/reactions.add",
      paramsSchema: {
        type: "object",
        properties: {
          channel: { type: "string", description: "Channel id the message is in." },
          timestamp: { type: "string", description: "Timestamp of the message to react to." },
          name: { type: "string", description: "Emoji name without colons, e.g. thumbsup." },
        },
        required: ["channel", "timestamp", "name"],
      },
    },
    {
      name: "join_channel",
      description: "Join the connected app to a public Slack channel.",
      method: "POST",
      path: "/conversations.join",
      paramsSchema: {
        type: "object",
        properties: { channel: { type: "string", description: "Channel id to join." } },
        required: ["channel"],
      },
    },
  ],
} satisfies ProviderDefInput;
