export {
  type AuthMode,
  type AuthRecipe,
  authModeSchema,
  authModes,
  authRecipeSchema,
  extractPlaceholders,
  type FieldDescriptor,
  fieldDescriptorSchema,
  githubProvider,
  interpolate,
  linearProvider,
  loadProviderCatalog,
  type McpTransport,
  mcpTransportSchema,
  notionMcpProvider,
  type OAuthActor,
  oauthActorSchema,
  type ProviderCatalog,
  ProviderCatalogValidationError,
  type ProviderDef,
  type ProviderDefInput,
  type ProviderHook,
  type ProviderHookRegistry,
  type ProviderHooks,
  type ProviderTransport,
  providerDefinitions,
  providerDefSchema,
  providerHookRegistry,
  providerHooksSchema,
  type RestTransport,
  restTransportSchema,
  TemplateInterpolationError,
  type TemplateValues,
  type ToolDefinition,
  toolDefinitionSchema,
  transportSchema,
} from "@trema/connectors";
export {
  buildOAuthAuthorizationUrl,
  ConnectorCatalogDefectError,
  ConnectorConnectionNotFoundError,
  type ConnectorFetch,
  ConnectorInstallationError,
  CredentialVerificationError,
  completeOAuthCallback,
  connectorCallbackUrl,
  consumeOAuthState,
  createStaticConnection,
  hashOAuthState,
  listConnectorConnections,
  OAuthStateExpiredError,
  OAuthStateSingleUseError,
  OAuthTokenExchangeError,
  revokeConnectorConnection,
  StaticCredentialValidationError,
  startOAuthConnect,
  UnsupportedConnectorAuthModeError,
  updateConnectorConnectionLabel,
} from "#server/services/connectors/connect.js";
export {
  ConnectorApprovalRequiredError,
  type ConnectorCallAuthority,
  ConnectorSsrfRejectedError,
  ConnectorTransportError,
  type ExecuteConnectorToolInput,
  executeConnectorTool,
  type McpConnectorToolResult,
  type ResolveConnectorToolInput,
  type RestConnectorToolResult,
} from "#server/services/connectors/execute.js";
export {
  type ConnectorConnectionHealth,
  type ConnectorConnectionHealthStatus,
  connectorConnectionHealthStatus,
  connectorConnectionValidity,
} from "#server/services/connectors/health.js";
export {
  type ArchiveConnectorInstallationInput,
  archiveConnectorInstallation,
  type ConnectorInstallationBody,
  ConnectorInstallationNotFoundError,
  ConnectorInstallationValidationError,
  type CreateConnectorInstallationInput,
  connectorInstallationBodySchema,
  createConnectorInstallation,
  createConnectorInstallationBodySchema,
  type InstallationAccess,
  installationAccessSchema,
  type ListConnectorInstallationHealthInput,
  type ListConnectorInstallationsInput,
  listConnectorInstallationHealth,
  listConnectorInstallations,
  type ResolvedInstallationTool,
  resolveInstallationTools,
  type SyncedTool,
  syncedToolSchema,
  type ToolAnnotations,
  toolAnnotationsSchema,
  type UpdateConnectorInstallationInput,
  updateConnectorInstallation,
} from "#server/services/connectors/installations.js";
export {
  buildMcpAuthorizationRequest,
  discoverMcpAuthServer,
  exchangeMcpAuthorizationCode,
  type McpAuthServer,
  McpOAuthDiscoveryError,
  type ResolvedMcpClient,
  type ResolveMcpClientRegistrationInput,
  resolveExistingMcpClientRegistration,
  resolveMcpClientRegistration,
  resolveStoredMcpClientRegistration,
} from "#server/services/connectors/mcp-oauth.js";
export {
  CONSERVATIVE_TOKEN_LIFETIME_SECONDS,
  type ConnectionCredentialPayload,
  ConnectorReconnectRequiredError,
  connectionNeedsRefresh,
  DEFAULT_TOKEN_EXPIRATION_BUFFER_SECONDS,
  REFRESH_FAILURE_BUDGET_MS,
  REFRESH_FAILURE_COOLDOWN_MS,
  type ResolveConnectionCredentialInput,
  type ResolvedConnectionCredential,
  resolveConnectionCredential,
} from "#server/services/connectors/refresh.js";
export {
  ClientRegistrationConflictError,
  ClientRegistrationNotFoundError,
  ClientRegistrationValidationError,
  ConnectorProviderNotFoundError,
  createClientRegistration,
  deleteClientRegistration,
  emptyPlatformAppDirectory,
  listClientRegistrations,
  NoClientRegistrationError,
  type PlatformApp,
  type PlatformAppDirectory,
  resolveClientRegistration,
  resolveStoredClientRegistration,
  validateRegistrationFields,
} from "#server/services/connectors/registrations.js";
export {
  type ConnectorAccessDenialReason,
  ConnectorAccessDeniedError,
  type ConnectorResolutionAuditBinding,
  type ConnectorResolutionContext,
  ConnectorToolNotAvailableError,
  ConnectorToolValidationError,
  type ResolvedConnectorInstallation,
  type ResolvedConnectorTool,
  resolveConnectorInstallation,
  resolveConnectorInstallations,
  resolveConnectorTool,
} from "#server/services/connectors/resolution.js";
export {
  ConnectorSyncTransportError,
  createStreamableHttpMcpClient,
  type McpClientFactory,
  type McpClientFactoryInput,
  type McpListedTool,
  type McpToolsClient,
  mapMcpTool,
  mergeSyncedTools,
  type SyncConnectorInstallationInput,
  type SyncReport,
  syncConnectorInstallation,
} from "#server/services/connectors/sync.js";
