export {
  loadProviderCatalog,
  type ProviderCatalog,
  ProviderCatalogValidationError,
} from "#/services/connectors/catalog.js";
export {
  buildOAuthAuthorizationUrl,
  ConnectorCatalogDefectError,
  ConnectorCredentialNotFoundError,
  type ConnectorFetch,
  ConnectorInstallationError,
  CredentialVerificationError,
  completeOAuthCallback,
  consumeOAuthState,
  createStaticCredential,
  hashOAuthState,
  listConnectorCredentials,
  OAuthStateExpiredError,
  OAuthStateSingleUseError,
  OAuthTokenExchangeError,
  revokeConnectorCredential,
  StaticCredentialValidationError,
  startOAuthConnect,
  UnsupportedConnectorAuthModeError,
} from "#/services/connectors/connect.js";
export {
  type ProviderHook,
  type ProviderHookRegistry,
  providerHookRegistry,
} from "#/services/connectors/hooks.js";
export {
  type ConnectorInstallationBody,
  ConnectorInstallationNotFoundError,
  ConnectorInstallationValidationError,
  ConnectorMemberConnectabilityError,
  type CreateConnectorInstallationInput,
  connectorInstallationBodySchema,
  createConnectorInstallation,
  createConnectorInstallationBodySchema,
  type ResolvedInstallationTool,
  resolveInstallationTools,
  type Sensitivity,
  type SyncedTool,
  sensitivities,
  sensitivitySchema,
  syncedToolSchema,
  type UpdateConnectorInstallationInput,
  updateConnectorInstallation,
} from "#/services/connectors/installations.js";
export {
  githubProvider,
  linearProvider,
  notionMcpProvider,
  providerDefinitions,
} from "#/services/connectors/providers/index.js";
export {
  ClientRegistrationConflictError,
  ClientRegistrationNotFoundError,
  ClientRegistrationValidationError,
  ConnectorProviderNotFoundError,
  createClientRegistration,
  deleteClientRegistration,
  emptyPlatformAppDirectory,
  listClientRegistrations,
  NoClientRegistrationError,
  type PlatformApp,
  type PlatformAppDirectory,
  resolveClientRegistration,
  resolveStoredClientRegistration,
  validateRegistrationFields,
} from "#/services/connectors/registrations.js";
export {
  type AuthMode,
  type AuthRecipe,
  authModeSchema,
  authModes,
  authRecipeSchema,
  type FieldDescriptor,
  fieldDescriptorSchema,
  type McpTransport,
  mcpTransportSchema,
  type ProviderDef,
  type ProviderDefInput,
  type ProviderHooks,
  type ProviderTransport,
  providerDefSchema,
  providerHooksSchema,
  type RestTransport,
  restTransportSchema,
  type ToolDefinition,
  toolDefinitionSchema,
  transportSchema,
} from "#/services/connectors/schema.js";
export {
  ConnectorSyncTransportError,
  createStreamableHttpMcpClient,
  type McpClientFactory,
  type McpClientFactoryInput,
  type McpListedTool,
  type McpToolsClient,
  mapMcpTool,
  mergeSyncedTools,
  type SyncConnectorInstallationInput,
  type SyncReport,
  sensitivityFromMcpAnnotations,
  syncConnectorInstallation,
} from "#/services/connectors/sync.js";
export {
  extractPlaceholders,
  interpolate,
  TemplateInterpolationError,
  type TemplateValues,
} from "#/services/connectors/templates.js";
