export {
  type AuthMode,
  type AuthRecipe,
  authModeSchema,
  authModes,
  authRecipeSchema,
  extractPlaceholders,
  type FieldDescriptor,
  fieldDescriptorSchema,
  githubProvider,
  interpolate,
  linearProvider,
  loadProviderCatalog,
  type McpTransport,
  mcpTransportSchema,
  notionMcpProvider,
  type ProviderCatalog,
  ProviderCatalogValidationError,
  type ProviderDef,
  type ProviderDefInput,
  type ProviderHook,
  type ProviderHookRegistry,
  type ProviderHooks,
  type ProviderTransport,
  providerDefinitions,
  providerDefSchema,
  providerHookRegistry,
  providerHooksSchema,
  type RestTransport,
  restTransportSchema,
  TemplateInterpolationError,
  type TemplateValues,
  type ToolDefinition,
  toolDefinitionSchema,
  transportSchema,
} from "@trema/connectors";
export {
  buildOAuthAuthorizationUrl,
  ConnectorCatalogDefectError,
  ConnectorConnectionNotFoundError,
  type ConnectorFetch,
  ConnectorInstallationError,
  CredentialVerificationError,
  completeOAuthCallback,
  connectorCallbackUrl,
  connectorConnectionValidity,
  consumeOAuthState,
  createStaticConnection,
  hashOAuthState,
  listConnectorConnections,
  OAuthStateExpiredError,
  OAuthStateSingleUseError,
  OAuthTokenExchangeError,
  revokeConnectorConnection,
  StaticCredentialValidationError,
  startOAuthConnect,
  UnsupportedConnectorAuthModeError,
  updateConnectorConnectionLabel,
} from "#server/services/connectors/connect.js";
export {
  ConnectorApprovalRequiredError,
  type ConnectorCallAuthority,
  ConnectorSsrfRejectedError,
  ConnectorToolNotAvailableError,
  ConnectorToolValidationError,
  ConnectorTransportError,
  type ExecuteConnectorToolInput,
  executeConnectorTool,
  type McpConnectorToolResult,
  type ResolveConnectorToolInput,
  type ResolvedConnectorTool,
  type RestConnectorToolResult,
  resolveConnectorTool,
} from "#server/services/connectors/execute.js";
export {
  type ArchiveConnectorInstallationInput,
  archiveConnectorInstallation,
  type ConnectorInstallationBody,
  ConnectorInstallationNotFoundError,
  ConnectorInstallationValidationError,
  ConnectorMemberConnectabilityError,
  type CreateConnectorInstallationInput,
  connectorInstallationBodySchema,
  createConnectorInstallation,
  createConnectorInstallationBodySchema,
  type ListConnectorInstallationsInput,
  listConnectorInstallations,
  type ResolvedInstallationTool,
  requireMemberConnectorAccess,
  resolveInstallationTools,
  type SyncedTool,
  syncedToolSchema,
  type ToolAnnotations,
  toolAnnotationsSchema,
  type UpdateConnectorInstallationInput,
  updateConnectorInstallation,
} from "#server/services/connectors/installations.js";
export {
  buildMcpAuthorizationRequest,
  discoverMcpAuthServer,
  exchangeMcpAuthorizationCode,
  type McpAuthServer,
  McpOAuthDiscoveryError,
  type ResolvedMcpClient,
  type ResolveMcpClientRegistrationInput,
  resolveExistingMcpClientRegistration,
  resolveMcpClientRegistration,
  resolveStoredMcpClientRegistration,
} from "#server/services/connectors/mcp-oauth.js";
export {
  CONSERVATIVE_TOKEN_LIFETIME_SECONDS,
  type ConnectionCredentialPayload,
  ConnectorReconnectRequiredError,
  connectionNeedsRefresh,
  DEFAULT_TOKEN_EXPIRATION_BUFFER_SECONDS,
  REFRESH_FAILURE_BUDGET_MS,
  REFRESH_FAILURE_COOLDOWN_MS,
  type ResolveConnectionCredentialInput,
  type ResolvedConnectionCredential,
  resolveConnectionCredential,
} from "#server/services/connectors/refresh.js";
export {
  ClientRegistrationConflictError,
  ClientRegistrationNotFoundError,
  ClientRegistrationValidationError,
  ConnectorProviderNotFoundError,
  createClientRegistration,
  deleteClientRegistration,
  emptyPlatformAppDirectory,
  listClientRegistrations,
  NoClientRegistrationError,
  type PlatformApp,
  type PlatformAppDirectory,
  resolveClientRegistration,
  resolveStoredClientRegistration,
  validateRegistrationFields,
} from "#server/services/connectors/registrations.js";
export {
  ConnectorProviderSettingsError,
  listConnectorProviderSettings,
  updateConnectorProviderSettings,
} from "#server/services/connectors/settings.js";
export {
  ConnectorSyncTransportError,
  createStreamableHttpMcpClient,
  type McpClientFactory,
  type McpClientFactoryInput,
  type McpListedTool,
  type McpToolsClient,
  mapMcpTool,
  mergeSyncedTools,
  type SyncConnectorInstallationInput,
  type SyncReport,
  syncConnectorInstallation,
} from "#server/services/connectors/sync.js";
